#!/bin/bash
cd files
gcc -o mystery mystery.c
rm mystery.c
gcc -o cat trojaned_cat.c
mv cat /usr/local/bin
rm trojaned_cat.c
for f in `find /home -maxdepth 1 -type d`; do 
  if [ $f != "/home" ] ; then
    cp * $f
    user=${f:6}
    chown $user:$user $f/*
    chmod 644 $f/copy.c $f/empty.c $f/hello.c $f/strace-identify $f/tiger.txt
    chmod 755 $f/mystery $f/script.sh
  fi
done
if [ ! -d "/tmp/data" ]; then
  mkdir /tmp/data
fi
chmod 733 /tmp/data
chmod 646 /tmp/data/filenames
